/* Auto-generated from APAC Marketing Calendar (NEW_Calendar_TEMPLATE) — last refresh: 2026-05-11 */
window.CALENDAR_EVENTS = [
  {
    "id": 1,
    "status": "🏁 Complete",
    "start": "1/11/2026",
    "end": "1/13/2026",
    "time": "",
    "name": "NRF ANZ Exec Engagement",
    "country": "🇦🇺 ANZ",
    "owner": "Gabby Song",
    "source": "Shopify Owned",
    "channel": "Sales Micro Event",
    "location": "NYC",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48362-NRF-26-AU-Exec-Engagement",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 2,
    "status": "🏁 Complete",
    "start": "1/29/2026",
    "end": "",
    "time": "",
    "name": "Australian Open Hospitality",
    "country": "🇦🇺 ANZ",
    "owner": "Gabby Song",
    "source": "Shopify Owned",
    "channel": "Sales Micro Event",
    "location": "Melbourne",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48035-AU-Australian-Open-Exec-Engagement-Jan-29-2026",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 3,
    "status": "🏁 Complete",
    "start": "2/13/2026",
    "end": "",
    "time": "",
    "name": "Partner: ECzine Day Session by TIS",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "TIS",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 4,
    "status": "🏁 Complete",
    "start": "2/18/2026",
    "end": "",
    "time": "",
    "name": "Partner: Why Direct 2026 Spring",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "HuckleBerry",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 5,
    "status": "🏁 Complete",
    "start": "2/19/2026",
    "end": "",
    "time": "",
    "name": "Partner: Weblife Webinar 売上を最大化する“Shopifyで勝てる戦略5選”",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "Weblife",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 6,
    "status": "🏁 Complete",
    "start": "2/27/2026",
    "end": "",
    "time": "",
    "name": "Partner: Ecommerce Fair Tokyo 2026_PM-APAC-JP",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "",
    "segment": "",
    "partner": "StoreHero",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 7,
    "status": "🏁 Complete",
    "start": "3/2/2026",
    "end": "",
    "time": "",
    "name": "Partner: The Global Commerce Summit 2026",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "R6B",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 8,
    "status": "🏁 Complete",
    "start": "3/17/2026",
    "end": "",
    "time": "",
    "name": "AI Campaign — Retail Innovation Forum Lead Gen",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "ABMモーションに組み込み済み。日程TBD"
  },
  {
    "id": 9,
    "status": "🏁 Complete",
    "start": "3/17/2026",
    "end": "",
    "time": "",
    "name": "AI Webinar 「ECサイト終焉」w/ 奥谷氏 x Tom",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48826-H1-26-ABM-2-0-Japan-Top-Accounts",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "TOFU/ABM; LP: commerce-innovation.jp/webinar/20260317; ~60 RSVPs as of 3/16; 15:00 JST"
  },
  {
    "id": 10,
    "status": "🏁 Complete",
    "start": "3/18/2026",
    "end": "",
    "time": "",
    "name": "Partner: The Future of Resale Business on Shopify Plus",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "Resort, Huckleberry",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 11,
    "status": "🏁 Complete",
    "start": "3/18/2026",
    "end": "",
    "time": "",
    "name": "Partner: Joint Webinar — Future of Resale Business on Shopify Plus",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "Resort",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; verify status with Reisa"
  },
  {
    "id": 12,
    "status": "🏁 Complete",
    "start": "3/19/2026",
    "end": "",
    "time": "",
    "name": "AI Campaign — GEO Playbook Blog (Localized)",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Blog Post",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "ローカライズ完了・社内レビュー済み。チェックリストPDF制作中（Infobahn）"
  },
  {
    "id": 13,
    "status": "🏁 Complete",
    "start": "3/19/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — Case Study - Relive",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "事例制作。チャンネルなし、手動更新"
  },
  {
    "id": 14,
    "status": "🔁 In Progress",
    "start": "3/20/2026",
    "end": "4/30/2026",
    "time": "",
    "name": "AI Webinar 「ECサイト終焉」w/ 奥谷氏 x Tom  On-Demand",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "https://commerce-innovation.jp/webinar/20260317_archive",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 15,
    "status": "🏁 Complete",
    "start": "3/23/2026",
    "end": "",
    "time": "11:00",
    "name": "AI Whitepaper Interview Part 1 — 藤原 × 中島聡",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "元ユナイテッドアローズ藤原 × 元MS中島聡の対談収録。WP制作用。Ayumi参加予定（オンライン）"
  },
  {
    "id": 16,
    "status": "✅ Confirmed",
    "start": "3/24/2026",
    "end": "",
    "time": "",
    "name": "Shopify Connect SYD",
    "country": "🇦🇺 ANZ",
    "owner": "Gabby Song",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "Sydney",
    "segment": "LA, MM, SMB",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48366-AU-Shopify-Connect-Series-SYD-MELB-Q1-2026",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 17,
    "status": "✅ Confirmed",
    "start": "3/24/2026",
    "end": "3/25/2026",
    "time": "",
    "name": "eTail Asia",
    "country": "🇸🇬 SEA",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 18,
    "status": "✅ Confirmed",
    "start": "3/25/2026",
    "end": "",
    "time": "",
    "name": "Plus Hub — AIテーマ IRL Event (BrainSleep りんごさん、Anker菅野さん他)",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "https://shopify-plushub.commmune.com/view/event/26945",
    "objective": "",
    "hero": "",
    "notes": "AI Sidekick活用事例テーマ; ANKER 菅野さん登壇調整中; 表参道会場"
  },
  {
    "id": 19,
    "status": "🔄 Planning",
    "start": "3/26/2026",
    "end": "",
    "time": "",
    "name": "Partner: Shopify Ecommerce Summit (Concentrix)",
    "country": "🇸🇬 SEA",
    "owner": "Esabelle Koh",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "MM",
    "partner": "Concentrix",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Korea-based; 30 expected leads, 2 PQLs"
  },
  {
    "id": 20,
    "status": "🏁 Complete",
    "start": "3/30/2026",
    "end": "",
    "time": "17:30",
    "name": "AI Whitepaper Interview Part 2 — 徳丸浩 × 須藤憲司",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "テーマ：AI時代の最新技術とセキュリティ。徳丸浩(EGセキュア) × 須藤憲司(Kaizen Platform CEO)"
  },
  {
    "id": 21,
    "status": "🏁 Complete",
    "start": "3/31/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — Case Study - Brain Sleep",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "事例制作。チャンネルなし、手動更新"
  },
  {
    "id": 22,
    "status": "🏁 Complete",
    "start": "3/31/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — Case Study - Moderato",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "事例制作。チャンネルなし、手動更新"
  },
  {
    "id": 23,
    "status": "🏁 Complete",
    "start": "3/31/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — Case Study - KURAND",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "事例制作。チャンネルなし、手動更新"
  },
  {
    "id": 24,
    "status": "🔁 In Progress",
    "start": "3/31/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — SEO blog x 1",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Gartnerとのメールプログラム。チャンネルなし、手動更新"
  },
  {
    "id": 25,
    "status": "🔁 In Progress",
    "start": "3/31/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — SEO blog x 2",
    "country": "s",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Gartnerとのメールプログラム。チャンネルなし、手動更新"
  },
  {
    "id": 26,
    "status": "🔁 In Progress",
    "start": "3/31/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — SEO blog x 3",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Gartnerとのメールプログラム。チャンネルなし、手動更新"
  },
  {
    "id": 27,
    "status": "✅ Confirmed",
    "start": "4/1/2026",
    "end": "5/30/2026",
    "time": "",
    "name": "Partner: Digital Transformation Campaign (The Working Party)",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Marketing Campaign",
    "location": "",
    "segment": "LA, MM",
    "partner": "The Working Party",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "40 exp. leads, 5 PQLs; Q2 TWP flagship campaign"
  },
  {
    "id": 28,
    "status": "🔄 Planning",
    "start": "4/1/2026",
    "end": "6/30/2026",
    "time": "",
    "name": "Partner: Fusion 5 — Paid Advertising",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "PocketSquare / Fusion 5",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; $4K USD"
  },
  {
    "id": 29,
    "status": "🔄 Planning",
    "start": "4/1/2026",
    "end": "5/30/2026",
    "time": "",
    "name": "Partner: Fusion 5 — AI Workshopping Session",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "PocketSquare / Fusion 5",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; $7K USD"
  },
  {
    "id": 30,
    "status": "🔄 Planning",
    "start": "4/1/2026",
    "end": "6/30/2026",
    "time": "",
    "name": "Partner: Aurora Project x Yiguo (GCR)",
    "country": "🇨🇳 GCR",
    "owner": "Elise Li",
    "source": "Partner-Led",
    "channel": "Marketing Campaign",
    "location": "",
    "segment": "MM",
    "partner": "Yiguo / Seel / GlobalE / Wati",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; 100 exp. leads, 4 PQLs; $50K USD"
  },
  {
    "id": 31,
    "status": "✅ Confirmed",
    "start": "4/2/2026",
    "end": "",
    "time": "",
    "name": "Partner: HK Commerce NEXT (WaveCommerce)",
    "country": "🇨🇳 GCR",
    "owner": "Elise Li",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "Hong Kong",
    "segment": "MM",
    "partner": "MindArc",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "60 exp. leads, 3 PQLs; $80K total budget"
  },
  {
    "id": 32,
    "status": "🔄 Planning",
    "start": "4/3/2026",
    "end": "",
    "time": "",
    "name": "AI Campaign — AI Disoverability Checklist (Localized)",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Blog Post",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "ローカライズ完了・社内レビュー済み。チェックリストPDF制作中（Infobahn）"
  },
  {
    "id": 33,
    "status": "✅ Confirmed",
    "start": "4/7/2026",
    "end": "",
    "time": "",
    "name": "重鎮プロジェクト Vol.2 — EC業界勉強会",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Quarterly EC industry leader Shopify study group; Vol.2"
  },
  {
    "id": 34,
    "status": "⏳ TBD",
    "start": "4/8/2026",
    "end": "",
    "time": "",
    "name": "Marketing Week Spring — Seminar Materials Deadline",
    "country": "🇯🇵 JP",
    "owner": "Ami Takane",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "Tokyo",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "登壇資料の提出締め切り。全セッション登壇者対応要"
  },
  {
    "id": 35,
    "status": "✅ Confirmed",
    "start": "4/10/2026",
    "end": "",
    "time": "",
    "name": "AI Webinar for Export Sellers",
    "country": "🇨🇳 GCR",
    "owner": "Nadine Coady",
    "source": "Other",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "All Merchants",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 36,
    "status": "🔄 Planning",
    "start": "4/10/2026",
    "end": "",
    "time": "",
    "name": "Trust-Building — Gartner MQ Japanese Report",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Gartnerとのメールプログラム。チャンネルなし、手動更新"
  },
  {
    "id": 37,
    "status": "🔄 Planning",
    "start": "4/14/2026",
    "end": "",
    "time": "4/17/2026",
    "name": "CxO Letter 第2弾 — 着弾 (日経クロストレンド同封)",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "ABM",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48826-H1-26-ABM-2-0-Japan-Top-Accounts",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Target: LA/MM H・M・L + SMB High; Highは手書き封筒; 日経クロストレンド2月号同封"
  },
  {
    "id": 38,
    "status": "🔄 Planning",
    "start": "4/14/2026",
    "end": "",
    "time": "4/17/2026",
    "name": "Invitation Gifting Program for 5月 CxO Roundtable — 経営層向け",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "ABM",
    "location": "",
    "segment": "",
    "partner": "Resort / GENIEE",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48826-H1-26-ABM-2-0-Japan-Top-Accounts",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "LA High Priority対象; MOFU engagement; 手紙 + ギフト同梱"
  },
  {
    "id": 39,
    "status": "🔄 Planning",
    "start": "4/15/2026",
    "end": "5/30/2026",
    "time": "",
    "name": "Partner: UnlockLAx36kr Marketing Campaign (Silk)",
    "country": "🇨🇳 GCR",
    "owner": "Elise Li",
    "source": "Partner-Led",
    "channel": "Marketing Campaign",
    "location": "",
    "segment": "LA, MM",
    "partner": "Silk",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; 100 exp. leads, 5 PQLs"
  },
  {
    "id": 40,
    "status": "🔄 Planning",
    "start": "4/15/2026",
    "end": "",
    "time": "",
    "name": "Partner: Weblife Shopify Roadmap Webinar",
    "country": "",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "Weblife",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 41,
    "status": "✅ Confirmed",
    "start": "4/16/2026",
    "end": "",
    "time": "",
    "name": "Partner: AI-Native EC Growth Strategy Webinar (Sidekick × GENIEE CDP)",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "Resort",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Joint co-webinar; ABM-relevant — check alignment with JP webinar calendar"
  },
  {
    "id": 42,
    "status": "🔄 Planning",
    "start": "4/20/2026",
    "end": "4/24/2026",
    "time": "",
    "name": "CxO Letter 第2弾 — BPO/BDR フォローアップ (コール + メール)",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "ABM",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48826-H1-26-ABM-2-0-Japan-Top-Accounts",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "GW明けアポ取り目標; 電話 + メールの並行フォロー"
  },
  {
    "id": 43,
    "status": "✅ Confirmed",
    "start": "4/21/2026",
    "end": "",
    "time": "",
    "name": "Partner: AI Decoded Event (MindArc)",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "8 exp. leads, 2 PQLs"
  },
  {
    "id": 44,
    "status": "✅ Confirmed",
    "start": "4/22/2026",
    "end": "4/23/2026",
    "time": "",
    "name": "AI Theme MOF 事例ウェビナー — 生活の木・中村さん登壇",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Sidekick AI活用事例テーマ; 登壇依頼書作成中 (山本さん); 日程TBD"
  },
  {
    "id": 45,
    "status": "✅ Confirmed",
    "start": "4/22/2026",
    "end": "4/24/2026",
    "time": "",
    "name": "iMedia Retail Summit Australia 2026",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "",
    "segment": "LA",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 46,
    "status": "🔁 In Progress",
    "start": "4/22/2026",
    "end": "",
    "time": "",
    "name": "AI Whitepaper AIコマース時代の生存戦略（仮）",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Other",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 47,
    "status": "✅ Confirmed",
    "start": "4/22/2026",
    "end": "",
    "time": "",
    "name": "Marketing Week Spring — Booth Day 1",
    "country": "🇯🇵 JP",
    "owner": "Ami Takane",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Tokyo",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "パートナーブース常駐: Resort + アパレルウェブ。Shopifyスタッフ AM/PMシフト対応"
  },
  {
    "id": 48,
    "status": "✅ Confirmed",
    "start": "4/23/2026",
    "end": "4/23/2026",
    "time": "",
    "name": "Plus Hub オンラインイベントー新常識！旧お客様アカウント廃止への対応と最新情報",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "X-Sell",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "https://shopify-plushub.commmune.com/view/event/27881",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 49,
    "status": "🔄 Planning",
    "start": "4/23/2026",
    "end": "5/18/2026",
    "time": "",
    "name": "Partner: ExporterChina Marketing Campaign (MeetSocial)",
    "country": "🇨🇳 GCR",
    "owner": "Elise Li",
    "source": "Partner-Led",
    "channel": "Marketing Campaign",
    "location": "",
    "segment": "MM",
    "partner": "MeetSocial",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; 100 exp. leads, 5 PQLs"
  },
  {
    "id": 50,
    "status": "✅ Confirmed",
    "start": "4/23/2026",
    "end": "",
    "time": "",
    "name": "Marketing Week Spring — Booth Day 2",
    "country": "🇯🇵 JP",
    "owner": "Ami Takane",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Tokyo",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "パートナーブース常駐: AMS + HuckleBerry。Takuya終日参加予定"
  },
  {
    "id": 51,
    "status": "✅ Confirmed",
    "start": "4/24/2026",
    "end": "",
    "time": "",
    "name": "Partner: Marketing Week Spring 2026_PM-APAC-JP",
    "country": "",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "",
    "segment": "",
    "partner": "StoreHero",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 52,
    "status": "✅ Confirmed",
    "start": "4/24/2026",
    "end": "",
    "time": "",
    "name": "Marketing Week Spring — Shopify Day (Stage Jack)",
    "country": "🇯🇵 JP",
    "owner": "Ami Takane",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Tokyo",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "4セッション: ①TikTok Shop×Collective (Junichi+TikTok Rong) ②AI UCP/GEO (Nobu+Stephenie) ③Edition/SimGym (Mizuki/Minami) ④CSM Thought Leadership+Sidekick (Keisuke/Saika/Tom). Lead info provided by RX Japan"
  },
  {
    "id": 53,
    "status": "🔄 Planning",
    "start": "4/29/2026",
    "end": "4/30/2026",
    "time": "",
    "name": "Partner: Taiwan Commerce Show (Kleis)",
    "country": "🇨🇳 GCR",
    "owner": "Elise Li",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "MM",
    "partner": "Kleis",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; 100 exp. leads, 3 PQLs"
  },
  {
    "id": 54,
    "status": "✅ Confirmed",
    "start": "4/29/2026",
    "end": "",
    "time": "",
    "name": "Shopify Connect MELB",
    "country": "🇦🇺 ANZ",
    "owner": "Gabby Song",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "Melbourne",
    "segment": "LA, MM, SMB",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/48366-AU-Shopify-Connect-Series-SYD-MELB-Q1-2026",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 55,
    "status": "🔄 Planning",
    "start": "5/1/2026",
    "end": "6/18/2026",
    "time": "",
    "name": "Partner: Fusion 5 — Future of Commerce Breakfast Event",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "PocketSquare / Fusion 5",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; $4K USD"
  },
  {
    "id": 56,
    "status": "⏳ TBD",
    "start": "5/5/2026",
    "end": "5/7/2026",
    "time": "",
    "name": "Retail Fest",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "",
    "segment": "SMB",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Vetting/Pending"
  },
  {
    "id": 57,
    "status": "✅ Confirmed",
    "start": "5/7/2026",
    "end": "",
    "time": "",
    "name": "Add to Cart retail event SYD",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "",
    "segment": "MM, SMB, X-Sell",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 58,
    "status": "🔄 Planning",
    "start": "5/14/2026",
    "end": "5/16/2026",
    "time": "",
    "name": "Partner: Automotive Aftermarket Expo (Soul and Wolf)",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "",
    "segment": "MM, SMB",
    "partner": "Soul and Wolf",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; 30 exp. leads, 5 PQLs; $25K AUD"
  },
  {
    "id": 59,
    "status": "✅ Confirmed",
    "start": "5/13/2026",
    "end": "",
    "time": "",
    "name": "Forefront Auckland Roundtable: AI Commerce in Practice",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Gilt Brasserie [Booked]\nThe Vault Private Dining Room\n2 Chancery Street, Chambers, Auckland 1010, NZ",
    "segment": "",
    "partner": "",
    "publication": "Forefront Events",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "AI Commerce in Practice: What's actually working for New Zealand retailers right now?\n• Hype vs real ROI: where AI is delivering and where it's not\n• How to move from pilot to scale without losing momentum\n• Preparing for agentic commerce: what technology and ecommerce leaders need to do now\n• Getting the whole business on board: the change management challenge nobody talks about",
    "notes": "24pax (15-18 Forefront delegates + 4 spots for client/vendor/moderator)\nSpeaker: James Johnson (for now)"
  },
  {
    "id": 60,
    "status": "✅ Confirmed",
    "start": "5/15/2026",
    "end": "",
    "time": "",
    "name": "Partner: Yarra Valley Event (Convert)",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "Yarra Valley",
    "segment": "MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "40 exp. leads, 10 PQLs"
  },
  {
    "id": 61,
    "status": "✅ Confirmed",
    "start": "5/19/2026",
    "end": "5/21/2026",
    "time": "",
    "name": "Partner: iMedia NZ (Moustache Republic)",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "",
    "segment": "",
    "partner": "Moustache Republic",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "NZ conference"
  },
  {
    "id": 62,
    "status": "✅ Confirmed",
    "start": "5/20/2026",
    "end": "",
    "time": "",
    "name": "K:SYD (Klaviyo Partner Event)",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "Sydney",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 63,
    "status": "✅ Confirmed",
    "start": "5/20/2026",
    "end": "",
    "time": "",
    "name": "Partner: KSYD Klaviyo Sponsorship",
    "country": "🌏 APAC",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "Sydney",
    "segment": "",
    "partner": "Convert / NORA",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "$10K Shopify contribution"
  },
  {
    "id": 64,
    "status": "🔄 Planning",
    "start": "5/20/2026",
    "end": "",
    "time": "(TBD)",
    "name": "AI Theme BOF 今やらなければならいことチェックリスト 5月企画",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "企画着手3/11; テーマ・登壇者TBD"
  },
  {
    "id": 65,
    "status": "✅ Confirmed",
    "start": "5/21/2026",
    "end": "",
    "time": "",
    "name": "Partner: NORA Showpo Bespoke Lunch (Convert)",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "",
    "segment": "LA, MM",
    "partner": "Resort / Huckleberry",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "LA/MM target accounts"
  },
  {
    "id": 66,
    "status": "✅ Confirmed",
    "start": "5/21/2026",
    "end": "",
    "time": "",
    "name": "Partner: OD & Chill x Body Shop (Overdose)",
    "country": "🇦🇺 ANZ",
    "owner": "Britta Davies",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "LA, MM",
    "partner": "Flagship",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "80 exp. leads, 8 PQLs; part of Unified Flywheel"
  },
  {
    "id": 67,
    "status": "✅ Confirmed",
    "start": "5/21/2026",
    "end": "",
    "time": "",
    "name": "Partner: Joint Offline Event — Present & Future of Shopify in Japan",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "Resort",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "⚠️ Near CxO Roundtable (5/20 TBD) — check for scheduling conflict"
  },
  {
    "id": 68,
    "status": "🔄 Planning",
    "start": "5/22/2026",
    "end": "",
    "time": "",
    "name": "Partner: Huckleberry Partner Roadshow Season 3",
    "country": "",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "Huckleberry",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 69,
    "status": "✅ Confirmed",
    "start": "5/26/2026",
    "end": "",
    "time": "",
    "name": "Partner: E-commerce Managers Forum 2026 Spring (Flagship)",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "",
    "segment": "",
    "partner": "Flagship",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 70,
    "status": "✅ Confirmed",
    "start": "4/30/2026",
    "end": "",
    "time": "",
    "name": "Forefront Melbourne Roundtable: AI Commerce in Practice",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Kisume [Booked]\nKuro Private Dining Room\n175 Flinders Lane, Melbourne VIC 3000",
    "segment": "",
    "partner": "",
    "publication": "Forefront Events",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "AI Commerce in Practice: What's actually working for Australian retailers right now?\n• Assessing AI hype vs real ROI and achieving practical wins in retail\n• How technology and ecommerce leaders can prepare for the shift to agentic commerce\n• Moving from pilot to scale and fostering enterprise-wide adoption",
    "notes": "22pax (15-18 Forefront delegates + 4 spots for client/vendor/moderator)\nSpeakers: James Johnson, Eduardo Frias"
  },
  {
    "id": 71,
    "status": "✅ Confirmed",
    "start": "6/2/2026",
    "end": "6/4/2026",
    "time": "",
    "name": "NRF APAC Shop & Sip x NORA",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Singapore",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 72,
    "status": "⏳ TBD",
    "start": "6/2/2026",
    "end": "6/4/2026",
    "time": "",
    "name": "NRF APAC",
    "country": "🇸🇬 SEA",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Singapore",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Vetting/Pending"
  },
  {
    "id": 73,
    "status": "🔄 Planning",
    "start": "6/2/2026",
    "end": "",
    "time": "",
    "name": "CxO ラウンドテーブル 「エージェンティックコマース~ AIが購買を代行する時代の経営戦略」",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "Tokyo",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 74,
    "status": "🔄 Planning",
    "start": "6/10/2026",
    "end": "",
    "time": "",
    "name": "Partner: Shopify POS Meetup & Talk Session (Apparel Web)",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "Apparel Web",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "⚠️ Same day as Commerce Summit Day 1 — verify with Reisa"
  },
  {
    "id": 75,
    "status": "🔄 Planning",
    "start": "6/10/2026",
    "end": "",
    "time": "",
    "name": "Commerce Summit — Day 1",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 76,
    "status": "⏳ TBD",
    "start": "6/11/2026",
    "end": "",
    "time": "",
    "name": "ARC Retail Awards 2026",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Melbourne",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Vetting/Pending"
  },
  {
    "id": 77,
    "status": "🔄 Planning",
    "start": "6/11/2026",
    "end": "",
    "time": "",
    "name": "Commerce Summit — Day 2",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 78,
    "status": "✅ Confirmed",
    "start": "6/12/2026",
    "end": "",
    "time": "",
    "name": "Partner: Commerce Summit 2026_PM-APAC-JP",
    "country": "",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Sponsorship",
    "location": "",
    "segment": "",
    "partner": "HuckleBerry",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 79,
    "status": "🔄 Planning",
    "start": "6/12/2026",
    "end": "",
    "time": "",
    "name": "Commerce Summit — Day 3",
    "country": "🇯🇵 JP",
    "owner": "Ayumi Manabe",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "TBD",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 80,
    "status": "🔄 Planning",
    "start": "6/16/2026",
    "end": "",
    "time": "",
    "name": "AI Campaign — Sponsored Media - NewsPicks",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "Apparel Web",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "媒体選定確定・配信タイミング合意済み。メディアSOW提出済み"
  },
  {
    "id": 81,
    "status": "✅ Confirmed",
    "start": "7/2/2026",
    "end": "",
    "time": "",
    "name": "Online Retail Breakfast",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Sydney",
    "segment": "LA, MM, SMB",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 82,
    "status": "⏳ TBD",
    "start": "7/2/2026",
    "end": "",
    "time": "",
    "name": "Retail Tech Osaka Day1",
    "country": "🇯🇵 JP",
    "owner": "Ami Takane",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Osaka",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 83,
    "status": "⏳ TBD",
    "start": "7/3/2026",
    "end": "",
    "time": "",
    "name": "Retail Tech Osaka Day2",
    "country": "🇯🇵 JP",
    "owner": "Ami Takane",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Osaka",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 84,
    "status": "✅ Confirmed",
    "start": "7/22/2026",
    "end": "",
    "time": "",
    "name": "Online Retail Sponsored Keynote",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Sydney",
    "segment": "All Merchants",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 85,
    "status": "⏳ TBD",
    "start": "9/22/2026",
    "end": "9/24/2026",
    "time": "",
    "name": "Retail Show Australia MEL",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Melbourne",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Vetting/Pending; Melbourne"
  },
  {
    "id": 86,
    "status": "🔄 Planning",
    "start": "4/?",
    "end": "",
    "time": "",
    "name": "AI Campaign — Sponsored Media - Nikkei Advertorial",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "媒体選定確定・配信タイミング合意済み。メディアSOW提出済み"
  },
  {
    "id": 87,
    "status": "🔄 Planning",
    "start": "5/?",
    "end": "",
    "time": "",
    "name": "AI Campaign — Sponsored Media - Nikkei Xtrend",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "媒体選定確定・配信タイミング合意済み。メディアSOW提出済み"
  },
  {
    "id": 88,
    "status": "🔄 Planning",
    "start": "5/?",
    "end": "",
    "time": "",
    "name": "AI Campaign — Sponsored Media - Nikkei Xtech",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "媒体選定確定・配信タイミング合意済み。メディアSOW提出済み"
  },
  {
    "id": 89,
    "status": "🔄 Planning",
    "start": "5/?",
    "end": "",
    "time": "",
    "name": "AI Campaign — Sponsored Media - JB Press CX Forum",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "Convert / Wishlist / Dotdigital",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "媒体選定確定・配信タイミング合意済み。メディアSOW提出済み"
  },
  {
    "id": 90,
    "status": "🔄 Planning",
    "start": "5/?",
    "end": "",
    "time": "",
    "name": "AI Campaign — Sponsored Media - JB Press AI Infra Forum",
    "country": "🇯🇵 JP",
    "owner": "Aoi Tanaka",
    "source": "Shopify Owned",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "Klaviyo",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "媒体選定確定・配信タイミング合意済み。メディアSOW提出済み"
  },
  {
    "id": 91,
    "status": "🔄 Planning",
    "start": "4/?",
    "end": "",
    "time": "(TBD)",
    "name": "Partner: Shopify Merchant × Partner Bootcamp (GCR)",
    "country": "🇨🇳 GCR",
    "owner": "Elise Li",
    "source": "Partner-Led",
    "channel": "Event - IRL",
    "location": "",
    "segment": "MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Proposed; 200 exp. leads, 4 PQLs; $20K USD"
  },
  {
    "id": 92,
    "status": "🔄 Planning",
    "start": "6/?",
    "end": "",
    "time": "(TBD)",
    "name": "Partner: Strategic Media Partnership with WWD JAPAN",
    "country": "🇯🇵 JP",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "Content Boost (Paid/Social)",
    "location": "",
    "segment": "",
    "partner": "Apparel Web",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Q2 content boost; date TBD"
  },
  {
    "id": 93,
    "status": "⏳ TBD",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "NORA AI Summit Sydney",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Sydney",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "August; Vetting/Pending"
  },
  {
    "id": 94,
    "status": "⏳ TBD",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "CEO Roundtable Sydney",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Sales Micro Event",
    "location": "Sydney",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "August; Vetting/Pending"
  },
  {
    "id": 95,
    "status": "⏳ TBD",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "NFL Exec Engagement",
    "country": "🇦🇺 ANZ",
    "owner": "Gabby Song",
    "source": "Shopify Owned",
    "channel": "Sales Micro Event",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "September; Vetting/Pending"
  },
  {
    "id": 96,
    "status": "⏳ TBD",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "Commerce Day",
    "country": "🇦🇺 ANZ",
    "owner": "Gabby Song",
    "source": "Shopify Owned",
    "channel": "Event - IRL",
    "location": "",
    "segment": "",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "October; Vetting/Pending"
  },
  {
    "id": 97,
    "status": "⏳ TBD",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "NORA AI Summit Melbourne",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Melbourne",
    "segment": "LA, MM",
    "partner": "",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "October; Vetting/Pending; Melbourne"
  },
  {
    "id": 98,
    "status": "⏳ TBD",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "The Business Show Australia",
    "country": "🇦🇺 ANZ",
    "owner": "Carlotta Criel",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Melbourne",
    "segment": "MM, SMB",
    "partner": "Event Marketing",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "November; Vetting/Pending"
  },
  {
    "id": 99,
    "status": "🔄 Planning",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "ARC Premium Boardroom Lunch",
    "country": "🇦🇺 ANZ",
    "owner": "Daniela Solomon",
    "source": "Shopify Owned",
    "channel": "Conference",
    "location": "Melbourne",
    "segment": "LA, MM",
    "partner": "Event Marketing",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Q3; Vetting/Pending"
  },
  {
    "id": 100,
    "status": "⏳ TBD",
    "start": "TBD",
    "end": "",
    "time": "TBD",
    "name": "Partner: Rewire Placeholder",
    "country": "",
    "owner": "Reisa Matsuda",
    "source": "Partner-Led",
    "channel": "",
    "location": "",
    "segment": "",
    "partner": "Rewire",
    "publication": "",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": ""
  },
  {
    "id": 101,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Unified Commerce Webinar: Buzzword or Business Strategy? - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/webinar/unified-commerce-buzzword-or-business-strategy?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=unified-commerce-forrester-webinar-en-AU-static-v1",
    "objective": "Q1 top performer. $58M influenced pipeline in AMER.",
    "hero": "Is unified commerce just a buzzword, or the strategy that gets you to your next growth milestone? | Unified Commerce: Buzzword or Business Strategy?",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: Carry Over | On-image: See AMER creative (Col O) | Chello: AMER carry-over. Use existing creative from Col O. No new design needed. | Q1 top performer. Prioritise for APAC Q2."
  },
  {
    "id": 102,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Skullcandy Case Study - Video + Static Video",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/case-studies/skullcandy?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=skull-candy-case-study-video-v1",
    "objective": "High brand recognition, strong creative",
    "hero": "It's one thing to replatform. It's another to do it in 90 days. See how Shopify helped Skullcandy move at breakneck speed. | Skullcandy: a story of speed",
    "notes": "Duration: Always-on | Ad format: Video | LinkedIn campaign: ABM_APAC_Video | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | VIDEO | Q226YEFNYV | LI objective: Website Visits | Carry over: Carry Over | On-image: See AMER creative (Col O) | Chello: AMER carry-over (video). Use existing creative from Col O. No new design needed."
  },
  {
    "id": 103,
    "status": "🔁 In Progress",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "Quad Lock Case Study (ANZ) - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/case-studies/quad-lock?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=quad-lock-case-study-static-v1",
    "objective": "15% D2C revenue YoY. 25% US/EU sales growth. $500M Thule acquisition. Melbourne-founded ANZ brand.",
    "hero": "15% D2C revenue growth, year over year. 25% growth in the US and EU. See how a Melbourne startup scaled to 56 markets on Shopify. | From Melbourne to 56 markets: how Quad Lock scaled D2C on Shopify",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: How Quad Lock built a global brand from Melbourne $500M\nacquisition | On-image: How Quad Lock built a global brand from Melbourne $500M\nacquisition | Chello: NEW ANZ asset. Visual hierarchy: hook text (line 1, regular weight) → $500M (hero stat, large + bold) → 'acquisition' (small, regular). Reference: approved Brand Collective ANZ ad format. Sizes: 1:1 + 4:5 static. | ANZ brand. Replaces Mocka Video (no video asset exists). Needs static creative."
  },
  {
    "id": 104,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Migration Guide / Time to Value - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Gated Content (ebook/whitepaper/website)",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/resource/time-to-value-guide?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=ttv-guide-static-v1",
    "objective": "All Accounts (no funnel segmentation)",
    "hero": "The real risk is standing still. Get the guide to faster migration. | Migrate faster with Shopify",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: Carry Over | On-image: See AMER creative (Col O) | Chello: AMER carry-over. Use existing creative from Col O. No new design needed."
  },
  {
    "id": 105,
    "status": "✅ Confirmed",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "Sidekick AI Prompt Playbook - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Gated Content (ebook/whitepaper/website)",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/resource/sidekick-ai-prompt-playbook?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=sidekick-ai-prompt-playbook-static-v1",
    "objective": "AMER proven at MOFU. Practical AI guide for ecommerce teams. Replaces Shop Pay Guide.",
    "hero": "20+ AI prompts to analyze, create, build, and automate, right inside your Shopify admin. | The AI prompt playbook for ecommerce teams",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: New (replaces Shop Pay Guide) | On-image: See AMER creative (Col O) | Chello: AMER carry-over. Use existing creative from Col O. No new design needed. | AMER proven. Use same static creative as AMER."
  },
  {
    "id": 106,
    "status": "🔁 In Progress",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "Australia Post: Inside Australian Online Shopping 2026 - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Gated Content (ebook/whitepaper/website)",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://auspost.com.au/business/ecommerce/ecommerce-report?cid=edm:5921618:bus:fy26_eCommerceReport_shopify:LK20260305002&utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=auspost-ecommerce-report-2026-static-v1",
    "objective": "3rd-party AU market research. 2026 data. $82.6bn AU online spend. Partner toolkit has ready-made LinkedIn copy and creative.",
    "hero": "Australian consumers spent a record $82.6bn online in 2025. See what's driving it and what it means for retailers right now. | Inside Australian Online Shopping 2026",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: New (replaces eCommerce Growth Guide) | On-image: See AusPost partner toolkit (Col O) | Chello: Use AusPost partner toolkit (Col O). No new design needed. | Use partner toolkit for creative | Shaun Broughton agentic commerce commentary included. Replaces eCommerce Growth Guide."
  },
  {
    "id": 107,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "TCO Webinar: How to improve your TCO by up to 36% - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/compare/tco/webinar?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=tco-webinar-static-v1",
    "objective": "All Accounts (no funnel segmentation)",
    "hero": "Platform costs don't have to keep climbing. See how retailers are cutting total cost of ownership by up to 36%. | How to cut your TCO by up to 36%",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: Carry Over | On-image: See AMER creative (Col O) | Chello: AMER carry-over. Use existing creative from Col O. No new design needed."
  },
  {
    "id": 108,
    "status": "🔁 In Progress",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Murad Case Study - Video",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/case-studies/murad?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=case-study-murad-video-v1",
    "objective": "56% conversion increase in 1 year",
    "hero": "A 56% conversion increase in just 1 year? That's what Murad unlocked after moving to Shopify. | Conversion starts on Shopify",
    "notes": "Duration: Always-on | Ad format: Video | LinkedIn campaign: ABM_APAC_Video | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | VIDEO | Q226YEFNYV | LI objective: Website Visits | Carry over: Carry Over | On-image: See AMER creative (Col O) | Chello: AMER carry-over (video). Use existing creative from Col O. No new design needed."
  },
  {
    "id": 109,
    "status": "🔁 In Progress",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "Nutrition Warehouse Case Study (ANZ) - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/case-studies/nutrition-warehouse?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=nutrition-warehouse-case-study-static-v1",
    "objective": "120+ stores on Shopify POS in 6 months. Magento migration. 15 min staff training. Strong ANZ omnichannel proof point.",
    "hero": "From Magento to 120 live stores in 6 months. Staff trained in 15 minutes on day one. See how Nutrition Warehouse runs it all on Shopify. | Nutrition Warehouse: 120 Shopify POS stores live in 6 months",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: How Nutrition Warehouse scaled fast 120\nstores in 6 months | On-image: How Nutrition Warehouse scaled fast 120\nstores in 6 months | Chello: NEW ANZ asset. Visual hierarchy: hook text (line 1, regular weight) → 120 (hero stat, large + bold) → 'stores in 6 months' (small, regular). Reference: approved Brand Collective ANZ ad format. Sizes: 1:1 + 4:5 static. | ANZ omnichannel + POS proof point. Needs static creative. Replaces TTV Contact Us Video."
  },
  {
    "id": 110,
    "status": "🔁 In Progress",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Metagenics Case Study (ANZ) - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/case-studies/metagenics?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=metagenics-case-study-static-v1",
    "objective": "67% YoY revenue increase, 25% conversion lift, full B2B + DTC in 6 months. LOCAL ANZ case study.",
    "hero": "B2B and DTC, both migrated to Shopify in 6 months. 67% revenue growth and 25% higher conversions. See how Metagenics did it. | Metagenics: 25% higher conversions after moving to Shopify",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: How Metagenics grew after moving to Shopify 67%\nrevenue growth in 6 months | On-image: How Metagenics grew after moving to Shopify 67%\nrevenue growth in 6 months | Chello: NEW ANZ asset. Visual hierarchy: hook text (line 1, regular weight) → 67% (hero stat, large + bold) → 'revenue growth in 6 months' (small, regular). Reference: approved Brand Collective ANZ ad format. Sizes: 1:1 + 4:5 static. | LOCAL ANZ case study. URL CONFIRMED LIVE: shopify.com/au/case-studies/metagenics. Still needs static creative asset."
  },
  {
    "id": 111,
    "status": "🔁 In Progress",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "4 Signs Your Tech Stack Is Holding You Back (AU blog) - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Blog Post",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/enterprise/blog/commerce-tech-stack-warnings?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=tech-stack-warnings-au-static-v1",
    "objective": "ANZ-ready. Problem-framing opener for cold audience.",
    "hero": "Four signs your tech stack is limiting your growth. See what Australia's leading retailers are doing instead. | What Australia's top retailers do differently",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: The hidden cost of the wrong platform Get the guide | On-image: The hidden cost of the wrong platform Read the article | Chello: NEW ANZ asset. Visual hierarchy: hook text (line 1, regular weight) → 'Read the article' (large + bold CTA). No merchant logo required. Sizes: 1:1 + 4:5 static. | ANZ-native blog. No localisation needed."
  },
  {
    "id": 112,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Digital Transformation Report: Integration vs Unification - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Gated Content (ebook/whitepaper/website)",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/resource/retail-digital-transformation-report?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=digital-transformation-report-gated-v1",
    "objective": "Forrester data. KEEN 80% TCO reduction. HERO ASSET.",
    "hero": "Integrated doesn't mean unified. See the data on what fragmentation is really costing retailers. | The Fragmentation Tax: Integration vs Unification",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: New | On-image: See AMER creative (pending Kelly) | Chello: AMER carry-over. Pending Kelly confirmation on APAC use rights. No new design needed. | HERO ASSET. Verify Forrester citation permissions for ANZ use."
  },
  {
    "id": 113,
    "status": "✅ Confirmed",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "Brand Collective Case Study (ANZ) - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/case-studies/brand-collective?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=brand-collective-case-study-static-v1",
    "objective": "19 brands on one platform. Team of 20 to 6. 60% IT overhead reduction. 10% YoY sales growth. Strongest ANZ enterprise transformation story.",
    "hero": "Brand Collective runs 19 brands with a team of 6. Before Shopify, it took a team of 20. Here's how they did it. | Brand Collective: 19 brands, one platform, 60% less overhead",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: \"Shopify gives us the space and resources to focus on our customers, products, and brands.\"\nBrand Collective\nAaron Gard, Group General Manager, Digital and Ecommerce | On-image: \"Shopify gives us the space and resources to focus on our customers, products, and brands.\"\nBrand Collective\nAaron Gard, Group General Manager, Digital and Ecommerce | Chello: NEW ANZ asset. Quote format: quote in \" \" (large text) → 'Brand Collective' (brand name, medium) → attribution name + title (small). Reference: approved APAC Brand Collective quote ad. Sizes: 1:1 + 4:5 static. Paid ad legal clearance TBC. | ANZ enterprise anchor proof point. Needs static creative. Published Sep 2025. Replaces Australian Retail Report 2024."
  },
  {
    "id": 114,
    "status": "🔁 In Progress",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "The Good Guys Case Study (ANZ, ENT) - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/case-studies/the-good-guys?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=the-good-guys-case-study-static-v1",
    "objective": "~20% online sales growth. 5x faster deployments. 2x site speed. 50% less campaign setup time. Headless Shopify on Hydrogen. Paid ad clearance unconfirmed.",
    "hero": "A custom platform that took days to update. Teams working through the night. The Good Guys fixed all of it on Shopify. | The Good Guys: 2x faster site, 50% less time on campaigns",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: How The Good Guys accelerated on Shopify 5x faster ~20% more online sales | On-image: How The Good Guys accelerated on Shopify 5x faster\n~20% more online sales | Chello: NEW ANZ asset. Visual hierarchy: hook text (line 1, regular weight) → '5x faster' (hero stat, large + bold) → '~20% more online sales' (regular). Reference: approved Brand Collective ANZ ad format. Sizes: 1:1 + 4:5 static. Paid ad legal clearance TBC. | ANZ digital transformation proof point. Headless on Hydrogen. Paid ad clearance unconfirmed. Replaces JB Hi-Fi."
  },
  {
    "id": 115,
    "status": "✅ Confirmed",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "Aviator Nation AI/Data Interview - Blog - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Blog Post",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/enterprise/blog/ai-unified-commerce-data-insights?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=aviator-nation-ai-blog-static-v1",
    "objective": "AMER proven at TOFU/MOFU. AI + unified data story. Creative exists (1x1 and 4x5). Request files from Kelly Mitchell.",
    "hero": "Shopify's AI assistant already knows your business. See how Aviator Nation put it to work. | Better data, smarter AI",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: New (replaces B2B Realities Blog) | On-image: See AMER creative (Col O) | Chello: AMER carry-over. Pending Kelly to provide 1:1 + 4:5 creative files. No new design needed. | AMER proven. Creative exists, request 1x1 and 4x5 from Kelly. Not AU-localised URL but works for APAC. Replaces B2B Realities Blog."
  },
  {
    "id": 116,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Your AI Discoverability Checklist - Static",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Gated Content (ebook/whitepaper/website)",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/resource/ai-discoverability-checklist?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=ai-discoverability-checklist-static-v1",
    "objective": "Runs across AMER at every funnel stage. Proven performer.",
    "hero": "AI search is how buyers find products now. Here's how to make sure yours show up. | Your guide to GEO and agentic-ready product data",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) | LinkedIn campaign: ABM_APAC_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | STATIC | Q226YEFNYV | LI objective: Website Visits | Carry over: Carry Over (AMER Proven) | On-image: See AMER creative (Col O) | Chello: AMER carry-over. Use existing creative from Col O. No new design needed. | AMER proven. Runs at all stages."
  },
  {
    "id": 117,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "Make AI Your Advantage - Contact Us Page - Static + Video",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Contact Us",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/enterprise?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=ai-advantage-contact-us-v1",
    "objective": "AMER runs at BOFU as static + video. AI-focused CTA.",
    "hero": "Create and launch campaigns faster with Shopify's built-in AI. | Make AI your unfair advantage",
    "notes": "Duration: Always-on | Ad format: Static (Single Image) + Video | LinkedIn campaign: ABM_APAC_BOF_Static | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | ACQ | CONVERSIONS | ABM | APAC-BoB | STATIC | Q226YEFNYV ABM_APAC_BOF_Video | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | ACQ | CONVERSIONS | ABM | APAC-BoB | VIDEO | Q226YEFNYV | LI objective: Lead Generation | Carry over: Carry Over (AMER Proven) | On-image: See AMER creative (Col O) | Chello: AMER carry-over. Use existing creative from Col O. No new design needed. | BOFU closer. Static + video versions."
  },
  {
    "id": 118,
    "status": "✅ Confirmed",
    "start": "3/27/2026",
    "end": "",
    "time": "",
    "name": "GEO Playbook - Exec Post Boost",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Executive Post",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/enterprise/blog/geo-playbook?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=geo-playbook-exec-post-v1",
    "objective": "Eduardo Frias + Sandy Jeong exec posts. AMER awareness tier.",
    "hero": "How brands are winning the AI search race. The GEO Playbook from Shopify. | The GEO Playbook",
    "notes": "Duration: Always-on | Ad format: Sponsored Post | LinkedIn campaign: ABM_APAC_ThoughtLeadership | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | AWARENESS | ABM | APAC-BoB | SPONSORED POST | Q226YEFNYV | LI objective: Post Engagement | Carry over: Carry Over (AMER Proven) | On-image: N/A - Exec Post | Thought Leadership campaign per Yash. Boost existing exec LinkedIn posts."
  },
  {
    "id": 119,
    "status": "✅ Confirmed",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "Agentic-Ready Product Data - Exec Post Boost",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Executive Post",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/resource/ai-discoverability-checklist?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=agentic-ready-product-data-exec-post-v1",
    "objective": "AMER exec posts. Sandy Jeong (ID #1362609146), Peyman N (ID #1362644266), Eduardo Frias (ID #1362770526), Dustin Holmstrom (ID #1362711096).",
    "hero": "Your buyers are already shopping through AI. Here's how to make sure your products show up ready. | Agentic-ready product data",
    "notes": "Duration: Always-on | Ad format: Sponsored Post | LinkedIn campaign: ABM_APAC_ThoughtLeadership | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | AWARENESS | ABM | APAC-BoB | SPONSORED POST | Q226YEFNYV | LI objective: Post Engagement | Carry over: New (Thought Leadership) | On-image: N/A - Exec Post | Boost existing AMER exec posts. Confirm post IDs with AMER team before launching. Sandy Jeong #1362609146, Peyman N #1362644266, Eduardo Frias #1362770526, Dustin Holmstrom #1362711096."
  },
  {
    "id": 120,
    "status": "🔁 In Progress",
    "start": "3/30/2026",
    "end": "",
    "time": "",
    "name": "The Good Guys Case Study (ANZ, ENT) - Video",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Shopify Owned",
    "channel": "Case Study",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "",
    "vault": "https://vault.shopify.io/gsd/projects/49984-Q2-Optimise-LinkedIn-Paid-ABM-Program-for-APAC-Mid-Market-and-Large-Accounts",
    "sf_link": "",
    "resource": "https://www.shopify.com/au/case-studies/the-good-guys?utm_source=linkedIn&utm_medium=cpm&utm_campaign=d2cretail_abm_apac_Q226YEFNYV&utm_content=the-good-guys-case-study-video-v1",
    "objective": "Video exists on Wistia: shopify-2.wistia.com/medias/6x95ouhs5j. Source MP4 from case study team. Paid ad clearance unconfirmed.",
    "hero": "A custom platform that took days to update. Teams working through the night. The Good Guys fixed all of it on Shopify. | The Good Guys: 2x faster site, 50% less time on campaigns",
    "notes": "Duration: Always-on | Ad format: Video | LinkedIn campaign: ABM_APAC_Video | BRAND | BAU | PLUS | LINKEDIN | APAC | High-PRIO-EN | EN | AW | WEBSITE VISITS | ABM | APAC-BoB | VIDEO | Q226YEFNYV | LI objective: Website Visits | Carry over: New | On-image: How The Good Guys accelerated on Shopify 5x faster\n~20% more online sales | Chello: NEW ANZ asset (video). On-image text applies to thumbnail/cover frame. Same visual hierarchy as Good Guys static (Row 19): hook → 5x faster (large/bold) → ~20% more online sales. Paid ad legal clearance TBC. | Video on Wistia confirmed. Request MP4 from case study team. Paid ad clearance unconfirmed."
  },
  {
    "id": 121,
    "status": "🔁 In Progress",
    "start": "4/10/2026",
    "end": "5/9/2026",
    "time": "",
    "name": "Inside Retail - 1 x sponsored content with exclusive roadblocks",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Sponsored Content",
    "location": "",
    "segment": "Upmarket",
    "partner": "Archetype (feature image)",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "https://insideretail.com.au/digital/retails-tech-trap-why-integration-is-not-unification-202604",
    "objective": "Awareness and problem framing",
    "hero": "Integration can connect systems, but it does not create a single source of truth—that's the difference between complexity and true readiness. Retailers are trying to deploy AI on fragmented stacks that the technology cannot reliably interpret.",
    "notes": "CTA: Visit unified commerce solutions page | Lead capture: N"
  },
  {
    "id": 122,
    "status": "🔁 In Progress",
    "start": "4/10/2026",
    "end": "5/9/2026",
    "time": "",
    "name": "Inside Retail - Roadblock ads (article exclusive)",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Display Ad",
    "location": "",
    "segment": "Upmarket",
    "partner": "Archetype",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "https://insideretail.com.au/digital/retails-tech-trap-why-integration-is-not-unification-202604",
    "objective": "Awareness",
    "hero": "Integration can connect systems, but it does not create a single source of truth—that's the difference between complexity and true readiness. Unified commerce is the foundation for GEO, because AI depends on clean, structured, real-time product and commerce data. And as discovery shifts from search to AI-driven selection, retailers need to understand GEO and what it takes to be surfaced, compared, and chosen.",
    "notes": "CTA: Visit unified commerce solutions page | Lead capture: N"
  },
  {
    "id": 123,
    "status": "🔁 In Progress",
    "start": "4/20/2026",
    "end": "5/1/2026",
    "time": "",
    "name": "Inside Retail - Roadblocks ads",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Display Ad",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "Roadblock ads: https://drive.google.com/drive/folders/1-46cvB8SNi7H69pr0YUYx-jqNK8cMKRP?usp=drive_link",
    "objective": "Awareness",
    "hero": "",
    "notes": "CTA: Read the article"
  },
  {
    "id": 124,
    "status": "🔁 In Progress",
    "start": "4/23/2026",
    "end": "4/23/2026",
    "time": "",
    "name": "Inside Retail - 1st solus EDM AU",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "Awareness",
    "hero": "Customer discovery is shifting. AI is changing how products are surfaced and selected",
    "notes": "CTA: Read the article | Lead capture: N"
  },
  {
    "id": 125,
    "status": "🔁 In Progress",
    "start": "5/2/2026",
    "end": "5/2/2026",
    "time": "",
    "name": "Inside Retail - 1st solus EDM NZ",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "Awareness",
    "hero": "Customer discovery is shifting. AI is changing how products are surfaced and selected",
    "notes": "CTA: Read the article | Lead capture: N"
  },
  {
    "id": 126,
    "status": "🔁 In Progress",
    "start": "4/28/2026",
    "end": "6/28/2026",
    "time": "",
    "name": "Inside Retail - 2 x months targeted LinkedIn lead gen boost",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Paid Social",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "Lead gen boost (approved copy): https://docs.google.com/document/d/13FBP6eck6xkIDz8uNI41zdBTWoB7q9Vn5QKszuOyylY/edit?tab=t.0",
    "objective": "Lead Capture",
    "hero": "GEO is the next evolution of digital discovery. Retailers need a practical framework, not hype",
    "notes": "CTA: Download the GEO Playbook | Lead capture: Y | Awaiting updated timeline on when they can go live"
  },
  {
    "id": 127,
    "status": "🔁 In Progress",
    "start": "5/1/2026",
    "end": "5/31/2026",
    "time": "",
    "name": "Inside Retail - 1 x leaderboard in Inside Retail AU daily newsbrief",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Display Ad",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "Leaderboard ad copy (approved copy): https://docs.google.com/document/d/13FBP6eck6xkIDz8uNI41zdBTWoB7q9Vn5QKszuOyylY/edit?tab=t.0",
    "objective": "Lead Capture",
    "hero": "GEO is the next evolution of digital discovery. Retailers need a practical framework, not hype",
    "notes": "CTA: Download the GEO Playbook | Lead capture: Y"
  },
  {
    "id": 128,
    "status": "🔁 In Progress",
    "start": "5/6/2026",
    "end": "5/6/2026",
    "time": "",
    "name": "Inside Retail - 1st Solus EDM AU retargeting",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "Lower-mid funnel",
    "hero": "If your systems are fragmented, AI cannot reliably evaluate, compare or transact on your products",
    "notes": "CTA: Visit unified commerce solutions page | Lead capture: N"
  },
  {
    "id": 129,
    "status": "🔁 In Progress",
    "start": "5/7/2026",
    "end": "5/7/2026",
    "time": "",
    "name": "Inside Retail - 1st solus EDM NZ retargeting",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "Lower-mid funnel",
    "hero": "If your systems are fragmented, AI cannot reliably evaluate, compare or transact on your products",
    "notes": "CTA: Visit unified commerce solutions page | Lead capture: N"
  },
  {
    "id": 130,
    "status": "🔁 In Progress",
    "start": "5/1/2026",
    "end": "5/31/2026",
    "time": "",
    "name": "Inside Retail - Roadblocks ads (lead capture)",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Display Ad",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "Roadblock ads: https://drive.google.com/drive/folders/1Zo_ttsCb7w8YibLA_HYsM-gVhKL4Ijc0",
    "objective": "Lead Capture",
    "hero": "GEO is the next evolution of digital discovery. Retailers need a practical framework, not hype",
    "notes": "CTA: Download the GEO Playbook | Lead capture: Y"
  },
  {
    "id": 131,
    "status": "🔁 In Progress",
    "start": "5/23/2026",
    "end": "5/23/2026",
    "time": "",
    "name": "Inside Retail - 2nd solus EDM AU",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "Lead Capture",
    "hero": "GEO is the next evolution of digital discovery. Retailers need a practical framework, not hype",
    "notes": "CTA: Download the GEO Playbook | Lead capture: Y"
  },
  {
    "id": 132,
    "status": "🔁 In Progress",
    "start": "6/24/2026",
    "end": "6/24/2026",
    "time": "",
    "name": "Inside Retail - 2nd solus EDM AU retargeting",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "",
    "hero": "",
    "notes": "CTA: Speak to Shopify | Lead capture: N"
  },
  {
    "id": 133,
    "status": "🔁 In Progress",
    "start": "6/1/2026",
    "end": "6/30/2026",
    "time": "",
    "name": "Inside Retail - 1 x leaderboard in Inside Retail NZ daily newsbrief",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Display Ad",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "Lead Capture",
    "hero": "Retailers are trying to win in an AI-driven discovery landscape with fragmented systems that lack a single source of truth—making their data unreliable, their stacks unreadable to AI, and leaving them unprepared to be surfaced, compared, and chosen.",
    "notes": "CTA: Download the GEO Playbook | Lead capture: Y"
  },
  {
    "id": 137,
    "status": "🔁 In Progress",
    "start": "5/7/2026",
    "end": "",
    "time": "",
    "name": "ITNews - 1 x solus EDM (inc geo targeting)",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "Chello",
    "publication": "ITNews",
    "vault": "",
    "sf_link": "",
    "resource": "N/A",
    "objective": "Lead Capture",
    "hero": "",
    "notes": "CTA: Download the GEO Playbook | Lead capture: N"
  },
  {
    "id": 138,
    "status": "🔁 In Progress",
    "start": "5/11/2026",
    "end": "5/11/2026",
    "time": "",
    "name": "Mi3 - 1 x native article featured for a week + shared via social and daily newsletter",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Sponsored Content",
    "location": "",
    "segment": "Upmarket",
    "partner": "n/a",
    "publication": "Mi3",
    "vault": "",
    "sf_link": "",
    "resource": "Draft title: Winning AI Discovery: From Search to Selection in the Age of Agentic Commerce (Archetype drafting)",
    "objective": "Awareness",
    "hero": "",
    "notes": "CTA: Download the GEO Playbook | Lead capture: N"
  },
  {
    "id": 139,
    "status": "🔁 In Progress",
    "start": "5/11/2026",
    "end": "5/11/2026",
    "time": "",
    "name": "Mi3 - 1 x ad display units to run simultaneously across their sites",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Display Ad",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "Mi3",
    "vault": "",
    "sf_link": "",
    "resource": "Draft copy: https://docs.google.com/document/d/1B6D9iY7pP3FhpfYgws3qFMEG_3kTntLYQbZzf7eToZ0/edit",
    "objective": "Lead Capture",
    "hero": "",
    "notes": "CTA: Download the GEO Playbook | Lead capture: N"
  },
  {
    "id": 140,
    "status": "🔁 In Progress",
    "start": "5/19/2026",
    "end": "",
    "time": "",
    "name": "AFR - 1st native article",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Sponsored Content",
    "location": "",
    "segment": "Upmarket",
    "partner": "n/a",
    "publication": "AFR",
    "vault": "",
    "sf_link": "",
    "resource": "Brief to AFR: https://docs.google.com/document/d/1UQ_m8n4Bm0ly7XpUb7y1DxKM1AdTDyzGNY3oVVlnaAU/edit",
    "objective": "Awareness",
    "hero": "",
    "notes": "CTA: N/A | Lead capture: N"
  },
  {
    "id": 141,
    "status": "🔁 In Progress",
    "start": "6/30/2026",
    "end": "",
    "time": "",
    "name": "AFR - 2nd native article",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Sponsored Content",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "AFR",
    "vault": "",
    "sf_link": "",
    "resource": "Brief to AFR (draft): https://docs.google.com/document/d/1EW5y1eFirTzw6zoz1ewsfuLOqBLZVi_Vkho7hs2Y3RE/edit",
    "objective": "Awareness",
    "hero": "",
    "notes": "CTA: N/A | Lead capture: N"
  },
  {
    "id": 144,
    "status": "🔁 In Progress",
    "start": "5/1/2026",
    "end": "",
    "time": "",
    "name": "Australian Retail Council - 2x co-branded solus eDMs + 2x ShopTalk Newsletters + 2x Social posts",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "Paid Media",
    "channel": "Email",
    "location": "",
    "segment": "Upmarket",
    "partner": "",
    "publication": "Australian Retail Council",
    "vault": "",
    "sf_link": "",
    "resource": "",
    "objective": "",
    "hero": "",
    "notes": "Reach: 27,000+ subscribers (eDMs), 12,000+ members (ShopTalk), 32,000+ followers (social)"
  },
  {
    "id": 145,
    "status": "✅ Confirmed",
    "start": "5/28/2026",
    "end": "",
    "time": "",
    "name": "[WEBINAR] AI commerce in practice: what enterprise retailers need before AI scales",
    "country": "🇦🇺 ANZ",
    "owner": "Shalini Karthikeyan",
    "source": "3rd Party Media / Publication",
    "channel": "Webinar/Virtual Event",
    "location": "",
    "segment": "All Merchants",
    "partner": "",
    "publication": "Inside Retail",
    "vault": "",
    "sf_link": "",
    "resource": "https://www.bigmarker.com/octomedia/ai-commerce-in-practice-what-enterprise-retailers-need-before-agentic-scales-8160aa270f54?show_live_page=true",
    "objective": "Lead Capture",
    "hero": "",
    "notes": "CTA: Attend webinar"
  }
];
window.CALENDAR_LAST_REFRESH = "2026-05-11";
